repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.2
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        exclude: '^modules|^example|^tools'
        args:
          - --args=--config=.config/terraform-docs.yml
      - id: terraform_validate
        exclude: ^examples
