repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
        args:
          - --unsafe
      - id: check-symlinks
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.2
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        exclude: '^modules|^example|^tools'
        args:
          - --args=--config=.config/terraform-docs.yml
      - id: terraform_validate
        exclude: ^examples
      - id: terraform_tflint
        exclude: ^examples
        args:
          - --args=--config=__GIT_WORKING_DIR__/.config/tflint.hcl
          - --env-vars=TFLINT_LOG="info"
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
