repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: pretty-format-json
        args:
          - --autofix
      - id: check-json
      - id: check-yaml
        args:
          - --unsafe
      - id: check-symlinks
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --args=--config=./.config/terraform-docs.yml
        exclude: "^modules|^examples|^tests"
      - id: terraform_validate
        exclude: "^examples|^tests"
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.config/tflint.hcl
          - --env-vars=TFLINT_LOG="info"
        exclude: "^examples|^tests"
      - id: terraform_tfsec
        exclude: "^examples|^tests"
